### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by impredicative** [klahnakoski/jx-python#1]
https://pypi.python.org/pypi/jx-python/ points to https://github.com/mozilla/jx-python . This is wrong!

**Comment by klahnakoski** [comment]
Thank you for catching this.  It is now [fixed](https://github.com/klahnakoski/jx-python/commit/d86f8cd93614f247b51a6d924384e7d0bb16417e#diff-2eeaed663bd0d25b7e608891384b7298R50)
